<a href="https://colab.research.google.com/github/sumitsng/Image-Classification/blob/master/Iris_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Iris Dataset

In [0]:
import sklearn
from sklearn.datasets import load_iris
import numpy as np
import keras
np.random.seed(10)
iris = load_iris()
print(iris)
#print(iris.data)

Using TensorFlow backend.


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

### Data Exploration

In [0]:
## Print type of iris
print(type(iris))

<class 'sklearn.utils.Bunch'>


In [0]:
## Print parent classes of this type
## Use the attribute __bases__ of the type that you have found
print(sklearn.utils.Bunch.__base__)

<class 'dict'>


So, you must have found that iris is a dict object

In [0]:
## Print the keys present in iris
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [0]:
## Create X and Y variables. X is the input features, Y is the output labels

In [0]:
X=[]
Y=[]
X=iris.data
Y=iris.target

In [0]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
## Track 5 random samples
isamples = np.random.randint(len(Y), size = (5))
print(isamples)

[  9 125  15  64 113]


In [0]:
#Shape of Data
print(iris.data.shape)
# Print shapes of X and Y
print(X.shape)
print(Y.shape)

(150, 4)
(150, 4)
(150,)


### Preprocess Data

#### Convert Labels(Y) to one-hot encoding 

In [0]:
### Convert Y to 1-hot encoding

##Your Code Here
def oneHot(y, Ny):
    '''
    Input:
        y: an int in {0, 1, 2}
        Ny: Number of classes, e.g., 3 here.
    Output:
        Y: a vector of Ny (=3) tuples
    '''
    Y = np.zeros(Ny)
    Y[y] = 1
    return Y
Ny = 3
Y= np.array([oneHot(y,Ny) for y in Y])

# Look at converted Y for the random samples we are t
print(Y[isamples])

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Its time to split your model into training and testing samples 

In [0]:
 from sklearn.model_selection import train_test_split
### split the data into 80% training and 20% testing
### Split X into two variables X_train and X_test
### Split Y correspondingly into two variables Y_train and Y_test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


### Data Normalization/Scaling


In [0]:
### Normalize data to be of zero mean and unit variance
def findMeanStddev(X):
    '''
    Input: 
        X: a matrix of size (no. of samples, dimension of each sample)
    Output:
        mean: mean of samples in X (same size as X)
        stddev: element-wise std dev of sample in X (same size as X)
    '''
    mean = np.sum(X, axis=0)/X.shape[0]
    X1 = X-mean
    stddev = np.sqrt(np.sum(X1*X1, axis=0)/X.shape[0])
    return mean, stddev

def normalizeX(X, mean, stddev):
    '''
    Input:
        X: a matrix of size (no. of samples, dimension of each sample)
        mean: mean of samples in X (same size as X)
        stddev: element-wise std dev of sample in X (same size as X) 
    Output:
        Xn: X modified to have 0 mean and 1 std dev
    '''
    Xn = (X-mean)/(stddev+1e-8)
    return Xn



Note: If the first 5 samples of X_train and Y_train looks like the one given below
then congratulations! You are on the right track;
If not, then persistance is the key to success :)


In [0]:
## Print and observe the normalized inputs and compare with older inputs
mean_train, stddev_train = findMeanStddev(X)
X = normalizeX(X, mean_train, stddev_train)
print(X)

[[-9.00681159e-01  1.01900433e+00 -1.34022652e+00 -1.31544428e+00]
 [-1.14301690e+00 -1.31979476e-01 -1.34022652e+00 -1.31544428e+00]
 [-1.38535264e+00  3.28414046e-01 -1.39706395e+00 -1.31544428e+00]
 [-1.50652050e+00  9.82172847e-02 -1.28338909e+00 -1.31544428e+00]
 [-1.02184903e+00  1.24920109e+00 -1.34022652e+00 -1.31544428e+00]
 [-5.37177552e-01  1.93979137e+00 -1.16971424e+00 -1.05217991e+00]
 [-1.50652050e+00  7.88807568e-01 -1.34022652e+00 -1.18381210e+00]
 [-1.02184903e+00  7.88807568e-01 -1.28338909e+00 -1.31544428e+00]
 [-1.74885624e+00 -3.62176237e-01 -1.34022652e+00 -1.31544428e+00]
 [-1.14301690e+00  9.82172847e-02 -1.28338909e+00 -1.44707646e+00]
 [-5.37177552e-01  1.47939785e+00 -1.28338909e+00 -1.31544428e+00]
 [-1.26418477e+00  7.88807568e-01 -1.22655167e+00 -1.31544428e+00]
 [-1.26418477e+00 -1.31979476e-01 -1.34022652e+00 -1.44707646e+00]
 [-1.87002411e+00 -1.31979476e-01 -1.51073880e+00 -1.44707646e+00]
 [-5.25060766e-02  2.16998813e+00 -1.45390137e+00 -1.31544428e

### Training time (using Neural Networks)

- create your NN model with given structure (4 input neurons, 8 hidden neurons and 3 output neurons)
- use 'relu' activation in hidden layer 
- use softmax activation in output
- Compile your model using 'categorical_crossentropy' loss function and sgd optimizer
- Track the accuracy metric of the model

In [0]:
from keras.models import Sequential
from keras.layers import Dense
import numpy
# fix random seed for reproducibility
#numpy.random.seed(7)
# create model
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
## Print the model summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 67
Trainable params: 67
Non-trainable params: 0
_________________________________________________________________


In [0]:
## Fit the model to data
model.fit(X_train, Y_train, epochs=150, batch_size=10)


Instructions for updating:
Use tf.cast instead.
Epoch 1/150
120/120 [==============================] - 1s 5ms/step - loss: 1.4798 - acc: 0.3167
Epoch 2/150
120/120 [==============================] - 0s 212us/step - loss: 0.9998 - acc: 0.3000
Epoch 3/150
120/120 [==============================] - 0s 186us/step - loss: 0.9147 - acc: 0.5000
Epoch 4/150
120/120 [==============================] - 0s 166us/step - loss: 0.8781 - acc: 0.5167
Epoch 5/150
120/120 [==============================] - 0s 184us/step - loss: 0.8573 - acc: 0.7250
Epoch 6/150
120/120 [==============================] - 0s 197us/step - loss: 0.8252 - acc: 0.7000
Epoch 7/150
120/120 [==============================] - 0s 186us/step - loss: 0.7859 - acc: 0.7667
Epoch 8/150
120/120 [==============================] - 0s 183us/step - loss: 0.7554 - acc: 0.7750
Epoch 9/150
120/120 [==============================] - 0s 176us/step - loss: 0.7219 - acc: 0.7833
Epoch 10/150
120/120 [==============================] - 0s 170us/step - 

In [0]:
## Test the accuracy of the model on test data
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)  # Evaluate the model
print('Accuracy :%0.3f, loss:%0.3f '%(accuracy,loss))

Accuracy :0.967, loss:0.156 


### Confusion Matrix and Accuracy

In [0]:
### Lastly, report the accuracy of your model and print the Confusion Matrix
loss, accuracy = model.evaluate(X, Y, verbose=0)  # Evaluate the model
print('Accuracy :%0.3f, loss:%0.3f '%(accuracy,loss))

Accuracy :0.573, loss:0.984 


In [0]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print( confusion_matrix(Y_test.argmax(axis=1), Y_pred.argmax(axis=1)) )


[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
