<a href="https://colab.research.google.com/github/sumitsng/Image-Classification/blob/master/MNIST_using_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classification of handwritten digits using Multi Layered Network

# MNIST Dataset

<img src="https://upload.wikimedia.org/wikipedia/commons/2/27/MnistExamples.png" title="MNIST dataset" align="center"/>



# Problem
Classify handwritten digits from 0 - 9. <br>
Each image is 28x28 pixels

<img src="https://corochann.com/wp-content/uploads/2017/02/mnist_plot.png" title="" align="center"/>


# Understanding the data

In [7]:
# MNIST data is present in the keras library. Load the data using load_data function of mnist
# Load the data into 4 variables - train_samples, train_labels, test_samples, test_labels
from keras.datasets import mnist
import tensorflow as tf
(train_samples, train_labels), (test_samples, test_labels) = tf.keras.datasets.mnist.load_data()
print(mnist)

<module 'keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/keras/datasets/mnist.py'>


### Shape of Data

In [8]:
## Print and observe the shapes of the 4 variables - train_samples, train_labels, test_samples, test_labels

train_samples.shape ,train_labels.shape, test_samples.shape ,test_labels.shape

((60000, 28, 28), (60000,), (10000, 28, 28), (10000,))

### Range of Values
Look at the range of values

In [9]:
import numpy as np
### Print max value of samples in train_samples
train_samples.max()

255

In [10]:
### Print min values of samples in train_samples
train_samples.min()


0

# Data Preparation

### Normalize inputs to (0, 1)

In [0]:
# Convert data type of elements in train_samples and test_samples from uint8 to float32
train_samples=train_samples.astype('float32')
test_samples=test_samples.astype('float32')

In [0]:
# Normalize inputs to (0,1)
# Divide train_samples and test_samples by max value of train_samples
train_samples/=255
test_samples/=255


### Convert outputs to 1-hot vectors

In [0]:
# convert train_labels and test_labels to 1-hot encoding
def one_hot_vector(Index):
  A = np.zeros(10)
  A[Index] = 1 
  return A
def one_hot_coding( label_list):
  A = np.empty((1,10))
  for index in label_list:
    tmp = one_hot_vector(index).reshape(1,10)
    A = np.concatenate((A,tmp ), axis = 0)
  A = np.delete(A ,0 ,0)
  return np.array(A)

labelTrain = one_hot_coding(train_labels)
labelTest = one_hot_coding(test_labels)

# Network Architecture

In [18]:
## Input is currently in the shape (samples, height, width)
## Reshape it such that it is suitable to be fed into a feed forward network

train = train_samples.reshape(-1,28,28,1)
test = test_samples.reshape(-1,28,28,1)
print(train.shape, test.shape)


(60000, 28, 28, 1) (10000, 28, 28, 1)


In [15]:
# Layer definitions
##Create a multi-layered neural network
## 1st hidden layer with 512 neurons and 'relu' activation
## 2nd hidden layer with 256 neurons and 'relu' activation
## Output layer with softmax activation
### Use Adam optimizer of keras
### Categorical cross entropy is loss

from keras.layers import Input, Dense
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense 
model = Sequential()
model.add(Convolution2D(32,3,2,activation='relu',input_shape = (28,28,1), use_bias= True,))
model.add(MaxPooling2D(3,1))
model.add(Convolution2D(64,2,1,activation='relu',use_bias=True))
model.add(Flatten())
model.add(Dense(units=10, activation='softmax'))
model.compile(optimizer= 'adam' , loss = 'categorical_crossentropy' , metrics = ['accuracy'])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 2), activation="relu", input_shape=(28, 28, 1..., use_bias=True)`
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (2, 1), activation="relu", use_bias=True)`
  # This is added back by InteractiveShellApp.init_path()


In [16]:
### Print summary of model and check if it is as desired. Also check total number of parameters to be trained.
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 27, 32)        224       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 24, 25, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 23, 25, 64)        4160      
_________________________________________________________________
flatten_1 (Flatten)          (None, 36800)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                368010    
Total params: 372,394
Trainable params: 372,394
Non-trainable params: 0
_________________________________________________________________


In [19]:
### Fit the model on train samples. Play with different values of epochs and batch_size. 
### See which gives the optimal result in the least amount of time.
model.fit( x = train , y = labelTrain , batch_size= 1000, epochs = 10 , verbose = 1  , validation_data = (test , labelTest), shuffle= True )


Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 9s 156us/step - loss: 0.4786 - accuracy: 0.8637 - val_loss: 0.1677 - val_accuracy: 0.9527
Epoch 2/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.1163 - accuracy: 0.9668 - val_loss: 0.0766 - val_accuracy: 0.9777
Epoch 3/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.0741 - accuracy: 0.9786 - val_loss: 0.0575 - val_accuracy: 0.9823
Epoch 4/10
60000/60000 [==============================] - 3s 50us/step - loss: 0.0592 - accuracy: 0.9829 - val_loss: 0.0551 - val_accuracy: 0.9815
Epoch 5/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.0498 - accuracy: 0.9852 - val_loss: 0.0487 - val_accuracy: 0.9842
Epoch 6/10
60000/60000 [==============================] - 3s 51us/step - loss: 0.0439 - accuracy: 0.9871 - val_loss: 0.0467 - val_accuracy: 0.9850
Epoch 7/10
60000/60000 [==============================] - 3s 51us/s

In [20]:
##Evaluate the model on test samples and print accuracy
loss , accuracy = model.evaluate(x = test , y = labelTest , batch_size= 1000)
print(loss , accuracy)

10000/10000 [==============================] - 0s 21us/step
0.04222300760447979 0.9865000247955322


In [23]:
### Print confusion matrix
Y_pred= model.predict(test)
from sklearn.metrics import confusion_matrix
print( confusion_matrix(labelTest.argmax(axis=1), Y_pred.argmax(axis=1)) )

[[ 973    0    2    0    0    1    1    1    1    1]
 [   0 1132    1    2    0    0    0    0    0    0]
 [   3    3 1013    0    1    0    2    7    2    1]
 [   1    0    3  993    0    5    0    3    4    1]
 [   0    0    0    0  976    0    1    1    0    4]
 [   2    0    1    3    0  883    2    1    0    0]
 [   9    2    1    0    1    3  941    0    1    0]
 [   0    1   10    1    0    1    0 1013    1    1]
 [   5    0    2    0    0    2    1    4  955    5]
 [   2    2    0    1    7    3    0    7    1  986]]
